<<<<<<< HEAD
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Deborah Saks
email: d_saks@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Collages by Deborah
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dscollage.com" # the base hostname & protocol for your site
twitter_username: debbiesakscollage
github_username:  debbie
=======
---
title: Your awesome title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
>>>>>>> b99eae5971f161f76597885f3b44528ef18035d4

'
baseurl: 
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
